import { Component } from '@angular/core';

@Component({
  selector: 'app-admin',
  templateUrl: './admin.component.html',
  styleUrls: ['./admin.component.scss'],
})
export class AdminComponent {
  adminSideNavPages: any[] = [
    {
      Id: 1,
      Code: 'ADMIN',
      Active: true,
      NameEn: 'Product',
      Icon: 'inventory_2',
      MasterPageId: 0,
      IsMaster: true,
      CanRead: true,
      CanWrite: true,
      ChildPages: [
        {
          Id: 4,
          Code: 'USERS',
          Active: true,
          NameEn: 'Approval',
          PageName: 'dashboard/admin/product/approval',
          Icon: 'check_circle',
          MasterPageId: 1,
          IsMaster: false,
          CanRead: true,
          CanWrite: true,
        },
      ],
    },
    {
      Id: 1,
      Code: 'ADMIN',
      Active: true,
      NameEn: 'User',
      PageName: 'dashboard/admin/users/listing',
      Icon: 'group',
      MasterPageId: 0,
      IsMaster: true,
      CanRead: true,
      CanWrite: true,
    },
    {
      Id: 1,
      Code: 'ADMIN',
      Active: true,
      NameEn: 'Orders',
      Icon: 'local_shipping',
      MasterPageId: 0,
      IsMaster: true,
      CanRead: true,
      CanWrite: true,
      ChildPages: [
        {
          Id: 4,
          Code: 'USERS',
          Active: true,
          NameEn: 'Listing',
          PageName: 'dashboard/admin/order/listing',
          Icon: 'reorder',
          MasterPageId: 1,
          IsMaster: false,
          CanRead: true,
          CanWrite: true,
        },
        {
          Id: 4,
          Code: 'USERS',
          Active: true,
          NameEn: 'Postage',
          PageName: 'dashboard/admin/order/postage',
          Icon: 'markunread_mailbox',
          MasterPageId: 1,
          IsMaster: false,
          CanRead: true,
          CanWrite: true,
        },
      ],
    },
    {
      Id: 1,
      Code: 'ADMIN',
      Active: true,
      NameEn: 'Print labels',
      Icon: 'print',
      MasterPageId: 0,
      IsMaster: true,
      CanRead: true,
      CanWrite: true,
      ChildPages: [
        {
          Id: 4,
          Code: 'USERS',
          Active: true,
          NameEn: 'Price',
          PageName: 'dashboard/admin/label/prices',
          Icon: 'point_of_sale',
          MasterPageId: 1,
          IsMaster: false,
          CanRead: true,
          CanWrite: true,
        },
        {
          Id: 4,
          Code: 'USERS',
          Active: true,
          NameEn: 'Listing',
          PageName: 'dashboard/admin/label/listing',
          Icon: 'reorder',
          MasterPageId: 1,
          IsMaster: false,
          CanRead: true,
          CanWrite: true,
        },
      ],
    },
  ];
}
